version: '3.8'

services:
    coordinator:
        image: trino-base-img:v0
        hostname: coordinator
        container_name: coordinator
        ports:
          - 8080:8080
        command: ["/bin/bash", "-c", "/workspace/trino/bin/launcher run & wait"]
        volumes:
          - ./coordinator:/workspace/trino/etc:ro

    worker-1:
        image: trino-base-img:v0
        hostname: worker-1
        container_name: worker-1
        command: ["/bin/bash", "-c", "/workspace/trino/bin/launcher run & wait"]
        volumes:
          - ./worker-1:/workspace/trino/etc:ro

    worker-2:
        image: trino-base-img:v0
        hostname: worker-2
        container_name: worker-2
        command: ["/bin/bash", "-c", "/workspace/trino/bin/launcher run & wait"]
        volumes:
          - ./worker-2:/workspace/trino/etc:ro
